export enum ErrorCodes {
  JWT_SECRET_NOT_DEFINED = "JWT_SECRET_NOT_DEFINED",
  TOKEN_VERIFICATION_FAILED = "TOKEN_VERIFICATION_FAILED",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  PASSWORD_MISMATCH = "PASSWORD_MISMATCH",
  PASSWORD_INVALID = "PASSWORD_INVALID",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  USER_ALREADY_LOGGED_IN = "USER_ALREADY_LOGGED_IN",
}
